name: tech-test-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ${{ github.workspace }}/UserManagement.Web/UserManagement.Web.csproj -c Release -o ${{ github.workspace }}/publish --no-build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tech-test-artifact            
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.5
      with:
        name: tech-test-artifact
        path: ${{ github.workspace }}/publish
        retention-days: 30
        overwrite: true
          
